redditclone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resource :session
  resources :subs
  resources :posts
end

  # resources :subs do
  #   resources :posts, only: [:create, :new]
  # end
  # resources :posts, except: [:create, :new]

redditclone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

redditclone/app/models/post.rb
class Post < ApplicationRecord
    validates :title, :sub_id, :author_id, presence: true

    has_many :post_subs,
        primary_key: :id,
        foreign_key: :post_id,
        class_name: :PostSub,
        inverse_of: :posts

    belongs_to :author,
        foreign_key: :author_id,
        class_name: :User

    has_many :subs,
        through: :post_subs,
        source: :subs
end

redditclone/app/models/post_sub.rb
class PostSub < ApplicationRecord
    validates :sub_id, presence: true
    validates :post_id, uniqueness: {scope: :sub_id}

    belongs_to :subs,
        foreign_key: :sub_id,
        class_name: :Sub

    belongs_to :posts,
        foreign_key: :post_id,
        class_name: :Post
end

redditclone/app/models/sub.rb
class Sub < ApplicationRecord
    validates :title, presence: true, uniqueness: true
    validates :description, :moderator_id, presence: true
    
    belongs_to :moderator,
        foreign_key: :moderator_id,
        class_name: :User

    has_many :post_subs,
        primary_key: :id,
        foreign_key: :sub_id,
        class_name: :PostSub,
        inverse_of: :subs

    has_many :posts,
        through: :post_subs,
        source: :posts
end

redditclone/app/models/user.rb
class User < ApplicationRecord
    validates :username, :session_token, presence: true, uniqueness: true
    validates :password, length: {minimum: 6}, allow_nil: true
    validates :password_digest, presence: true

    attr_reader :password

    after_initialize :ensure_session_token

    has_many :subs,
        foreign_key: :moderator_id,
        class_name: :Sub

    has_many :posts,
        foreign_key: :author_id,
        class_name: :Post

    def self.find_by_credentials(username, password)
        user = User.find_by(username: username)
        if user && user.is_password?(password)
            user
        else
            nil
        end
    end

    def password=(password)
        @password = password
        self.password_digest = BCrypt::Password.create(password)
    end

    def is_password?(password)
        BCrypt::Password.new(self.password_digest).is_password?(password)
    end

    def reset_session_token!
        self.session_token = SecureRandom::urlsafe_base64
        self.save!
        self.session_token
    end

    def ensure_session_token
        self.session_token ||= SecureRandom::urlsafe_base64
    end
end

redditclone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find_by(session_token: session[:session_token])
    end

    def require_logged_in
        redirect_to new_session_url unless logged_in?
    end

    def logged_in?
        !!current_user
    end

    def login!(user)
        user.reset_session_token!
        session[:session_token] = user.session_token
        current_user = user
    end

    def logout!
        @current_user.reset_session_token!
        session[:session_token] = nil
        @current_user = nil
        redirect_to new_session_url
    end



    


end

redditclone/app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :post_owner? , only: [:edit, :update, :destroy]
    before_action :require_logged_in, except: [:show, :index]

    def post_owner?
        current_user.posts.find_by(id: params[:id])
    end

    def new
        @post = Post.new
        render :new
    end

    def create
        @post = Post.new(post_params)
        @post.author_id = current_user.id
        if @post.save 
            redirect_to post_url(@post)
        else
            flash[:errors] = @post.errors.full_messages
            render :new
        end
    end

    def show
        @post = Post.find_by(id: params[:id])
        render :show
    end

    def edit
        @post = Post.find_by(id: params[:id])
        render :edit
    end

    def update
        @post = Post.find_by(id: params[:id])
        if @post.update(post_params) && current_user.id == @post.author_id
            redirect_to post_url(@post)
        else
            flash[:errors] = @post.errors.full_messages
            render :edit
        end
    end

    def destroy
        @post = Post.find_by(id: params[:id])
        @post.destroy if current_user == @post.author_id
        redirect_to subs_url
    end

    private
    def post_params
        params.require(:post).permit(:title, :url, :content, sub_ids: [])
    end
end

redditclone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :require_logged_in, only: [:destroy]

    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
        if @user
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = ['Invalid username or password']
            render :new
        end
    end

    def destroy
        logout!
    end
end

redditclone/app/controllers/subs_controller.rb
class SubsController < ApplicationController
    before_action :sub_owner? , only: [:edit, :update, :destroy]
    before_action :require_logged_in, except: [:show, :index]
    def sub_owner?
        current_user.subs.find_by(id: params[:id])
    end

    def new
        @sub = Sub.new
        render :new
    end

    def create
        @sub = Sub.new(sub_params)
        @sub.moderator_id = current_user.id
        if @sub.save 
            redirect_to sub_url(@sub)
        else
            flash[:errors] = @sub.errors.full_messages
            render :new
        end
    end

    def show
        @sub = Sub.find_by(id: params[:id])
        render :show
    end

    def index
        @subs = Sub.all
        render :index
    end

    def edit
        @sub = Sub.find_by(id: params[:id])
        render :edit
    end

    def update
        @sub = Sub.find_by(id: params[:id])
        if @sub.update(sub_params) && current_user.id == @sub.moderator_id
            redirect_to sub_url(@sub)
        else
            flash[:errors] = @sub.errors.full_messages
            render :edit
        end
    end

    def destroy
        @sub = Sub.find_by(id: params[:id])
        @sub.destroy if current_user == @sub.moderator_id
        redirect_to subs_url
    end

    private
    def sub_params
        params.require(:sub).permit(:title, :description)
    end

end

redditclone/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_logged_in, only: [:edit, :update, :destroy]
    
    def new
        @user = User.new
        render :new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            login!(@user)
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :new
        end
    end

    def index
        @users = User.all
        render :index
    end

    def show
        @user = User.find_by(id: params[:id])
        render :show
    end

    def edit
        @user = User.find_by(id: params[:id])
        render :edit
    end

    def update
        @user = User.find_by(id: params[:id])
        if @user.update(user_params) && current_user == @user
            redirect_to user_url(@user)
        else
            flash.now[:errors] = @user.errors.full_messages
            render :edit
        end
    end

    def destroy
        @user = User.find_by(id: params[:id])
        @user.destroy
        redirect_to new_session_url
    end

    private
    def user_params
        params.require(:user).permit(:username, :password)
    end
end

redditclone/app/helpers/application_helper.rb
module ApplicationHelper
end

redditclone/app/helpers/posts_helper.rb
module PostsHelper
end

redditclone/app/helpers/sessions_helper.rb
module SessionsHelper
end

redditclone/app/helpers/subs_helper.rb
module SubsHelper
end

redditclone/app/helpers/users_helper.rb
module UsersHelper
end

redditclone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redditclone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Reddit</h1>
    <% if logged_in? %>
      <%= current_user.username%>
      <a href="<%= new_sub_url%>">Create a Sub</a>
      <a href="<%= subs_url%>">All Subs</a>
      <form action="<%= session_url %>" method = "POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Sign Out">
      </form>

    <% else %>
      <a href="<%= new_user_url%>">Sign Up</a>
      <a href="<%= new_session_url%>">Sign In</a>
    <% end %>

    <% if flash[:errors] %>
      <%= flash[:errors]%>
    <% end %>
    <%= yield %>
  </body>
</html>

redditclone/app/views/posts/edit.html.erb
<h2>Edit Post</h2>
<form action="<%= post_url(@post) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
     <input type="hidden" name="_method" value="PATCH">
    <label>Title:
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>
    <label>URL:
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>
    <label>Content:
        <textarea name="post[content]"><%= @post.content %></textarea>
    </label>
    <% Sub.all.each do |sub| %>
    <label><%= sub.title %>:
    <input type="checkbox" name="post[sub_id][]" value="<%= sub.id %>"
    <%= "checked" if @post.sub_ids.include?(sub_id) %>>
    </label>
    <% end %>
    <input type="submit" value="Edit Post">
</form>

redditclone/app/views/posts/new.html.erb
<h2>Make a New Post</h2>
<form action="<%= posts_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Title:
        <input type="text" name="post[title]" value="<%= @post.title %>">
    </label>
    <label>URL:
        <input type="text" name="post[url]" value="<%= @post.url %>">
    </label>
    <label>Content:
        <textarea name="post[content]"><%= @post.content %></textarea>
    </label>
    <input type="hidden" name="post[sub_ids][]" value="">
    <% Sub.all.each do |sub| %>
    <label><%= sub.title %>:
        <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"
        <%= "checked" if @post.sub_ids.include?(sub.id) %>>
    </label>
    <% end %>
    <input type="submit" value="Post">
</form>

redditclone/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<h2>by <%= @post.author.username %></h2>

<body>Content:
    <br>
    <%= @post.content %>
</body>

<a href="<%= edit_post_url(@post) %>">Edit Post</a>

redditclone/app/views/subs/edit.html.erb
<h2>Edit Sub</h2>
<form action="<%= sub_url(@sub) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">
    <label>Title:
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <label>Description:
        <textarea name="sub[description]" value="<%= @sub.description %>"></textarea>
    </label>
    <input type="submit" value="Submit">
</form>

redditclone/app/views/subs/index.html.erb
<h1>All the Subs</h1>

<ul>
    <% @subs.each do |sub| %>
        <li><a href="<%= sub_url(sub)%>"><%= sub.title%></a></li>
    <% end %>
</ul>

redditclone/app/views/subs/new.html.erb
<h2>Make a New Sub</h2>
<form action="<%= subs_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Title:
        <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <label>Description:
        <textarea name="sub[description]" value="<%= @sub.description %>"></textarea>
    </label>
    <input type="submit" value="Submit">
</form>

redditclone/app/views/subs/show.html.erb
<h1><%= @sub.title%></h1>
<h4>Description:</h4>
<p><%= @sub.description%></p>
<a href="<%= new_post_url %>">Create a Post</a>
<ul>
    <% @sub.posts.each do |post| %>
        <li><a href="<%= post_url(post)%>"><%= post.title%></a></li>
    <% end %>
</ul>
<a href="<%= edit_sub_url%>">Edit Sub</a>

redditclone/app/views/users/edit.html.erb
<h2>Edit User</h2>
<form action="<%= user_url(@user) %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="PATCH">
    <label>Username:
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>
    <label>Password:
        <input type="password" name="user[password]" value="<%= @user.password %>">
    </label>
    <input type="submit" value="Edit User">
</form>

redditclone/app/views/users/index.html.erb
<h1>All Users</h1>

<ul>
    <%@users.each do |user| %>
        <li><a href="<%= user_url(user)%>"><%= user.username%></a></li>
    <% end %>

</ul>

redditclone/app/views/users/new.html.erb
<h2>Create New User</h2>
<form action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label>Username:
        <input type="text" name="user[username]" value="<%= @user.username %>">
    </label>
    <label>Password:
        <input type="password" name="user[password]" value="<%= @user.password %>">
    </label>
    <input type="submit" value="Sign Up">
</form>

redditclone/app/views/users/show.html.erb
<h2><%=@user.username%>'s Profile</h2>
    <form action="<%= users_url %>" method = "GET">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="submit" value="All Users">
    </form>

    <% if logged_in? && current_user.id == @user.id %>
        <form action="<%= edit_user_url(@user)%>" method = "GET">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="submit" value="Edit User">
        </form>

        <form action="<%= user_url(@user) %>" method = "POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="DELETE USER">
        </form>
    <% end %>